# Generated by Django 5.2.17 on 2026-08-25 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('unidade_medida', models.CharField(max_length=50)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_minima', models.IntegerField()),
                ('tipo_uso', models.CharField(choices=[('LANCHE', 'Lanche'), ('ALMOCO', 'Almoço')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100)),
                ('data_validade', models.DateField()),
                ('quantidade_atual', models.IntegerField(default=0)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='alimentos.alimento')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('quantidade', models.IntegerField()),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='alimentos.lote')),
            ],
        ),
    ]
