# Generated by Django 4.2.30 on 2026-09-18 12:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('embalagem', models.CharField(choices=[('PACOTE', 'Pacote'), ('CAIXA', 'Caixa'), ('LATA', 'Lata'), ('VIDRO', 'Vidro'), ('GARRAFA', 'Garrafa'), ('POTE', 'Pote'), ('SACO', 'Saco')], max_length=20)),
                ('quantidade_embalagem', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('unidade_medida', models.CharField(choices=[('KG', 'kg'), ('G', 'g'), ('L', 'L'), ('ML', 'ml')], max_length=5)),
                ('quantidade_minima', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tipo_uso', models.CharField(choices=[('LANCHE', 'Lanche'), ('ALMOCO', 'Almoço')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100)),
                ('quantidade_atual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('data_validade', models.DateField()),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='alimentos.alimento')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('data_movimentacao', models.DateField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='alimentos.lote')),
            ],
        ),
    ]
