# Generated by Django 6.1.1 on 2026-10-01 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: 058', max_length=10, unique=True)),
                ('nome', models.CharField(help_text='Ex: Etec Euro Albino de Souza', max_length=150)),
                ('cidade', models.CharField(help_text='Ex: Araras', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='alimento',
            name='etec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alimentos', to='alimentos.etec'),
        ),
        migrations.AddField(
            model_name='lote',
            name='etec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='alimentos.etec'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprovado_diretora', models.BooleanField(default=False)),
                ('etec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='alimentos.etec')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
