# Generated by Django 5.2.17 on 2026-08-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='data_movimentacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
