# Generated by Django 6.1 on 2026-08-31 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0002_alter_movimentacao_data_movimentacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='quantidade_embalagem',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='quantidade_minima',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='lote',
            name='quantidade_atual',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='quantidade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
