# Generated by Django 6.1.1 on 2026-10-02 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0002_perfil_email_verificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='etec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='alimentos.etec'),
        ),
    ]
