# Generated by Django 5.2.17 on 2026-09-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0003_alter_alimento_quantidade_embalagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('DESCARTE', 'Descarte')], max_length=10),
        ),
    ]
